version: "3"

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=${GRAPH_DB_NAME}
      - MYSQL_ROOT_PASSWORD=${GRAPH_DB_PASS}
      - MYSQL_USER=${DB_API_USER}
      - MYSQL_PASSWORD=${DB_API_PASS}
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - 3306:3306
    volumes:
      - ./backend/tmp/db:/var/lib/mysql
  api:
    build:
      context: ./backend/
      dockerfile: ${DOCKERFILE}
      args:
        - master_key=${RAILS_MASTER_KEY}
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    image: rails.dev
    volumes:
      - ./backend:/api
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: ${RAILS_ENV}
      DB_API_USER: ${DB_API_USER}
      DB_API_PASS: ${DB_API_PASS}
    ports:
      - 3001:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
  front:
    image: node:19.3.0-alpine3.17
    volumes:
      - ./frontend/app:/usr/src/app
      - ./frontend/app/node_modules_volume:/app/node_modules
    working_dir: /usr/src/app/node_modules
    command: sh -c "yarn install && yarn add react-bootstrap bootstrap && yarn start"
    ports: 
      - "4000:3000"
volumes:
  mysql-data:
